### ISSUE TITLE
Reduce MAX_PING_INTERVAL by 5mins

### ISSUE THREAD

**Issue by codeshifu** [codeshifu/pingmydyno#1]
Currently, the MAX_PING_INTERVAL is set to 30mins which is the same time it takes for a dyno to go idle when it doesn't receive any web traffic. This will cause `pingmydyno` not to get called if it's included as part of the app being pinged.

Reducing the MAX_PING_INTERVAL by 5 - 10mins will ensure `pingmydyno` always do its job and keep the dyno awake forever.

**Comment by akhilome** [comment]
Let me hop on this. @codeshifu 😀
